version: "3.8"
services:
  backend:
    image: ghcr.io/olivier-stoked/m324backend:latest
    ports:
      - "8080:8080"
  frontend:
    image: ghcr.io/olivier-stoked/m324frontend:latest
    ports:
      - "80:80"
